### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_cloudwatch#1]
Hey @cammellos, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are the original contributor of the CloudWatch service to ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

Thank you!

**Comment by cammellos** [comment]
Hi Ben,
Sounds good to me,
Thanks!

**Comment by benwilson512** [comment]
Thanks! You have been given write access to this repository.
