### ISSUE TITLE
Dimensions are not being correctly prefixed.

### ISSUE THREAD

**Issue by CaldwellYSR** [ex-aws/ex_aws_cloudwatch#5]
Metric data is all prefixed with `MetricData.member` correctly but dimensions are getting jammed together instead of being prefixed appropriately. 

This is the request params that are output from `put_metric_data/2`
```
%{
   "Action" => "PutMetricData",
   "MetricData.member.Dimensions.JobsCount" => "Jobs",
   "MetricData.member.MetricName" => "JobsCount",
   "MetricData.member.Unit" => "Count",
   "MetricData.member.Value" => 0,
   "Namespace" => "Dev/Jobs",
   "Version" => "2010-08-01"
 }
```

These are the expected params from [the docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html)
```
https://monitoring.&api-domain;/doc/2010-08-01/
?Action=PutMetricData
&Version=2010-08-01
&Namespace=TestNamespace
&MetricData.member.1.MetricName=buffers
&MetricData.member.1.Unit=Bytes
&MetricData.member.1.Value=231434333
&MetricData.member.1.Dimensions.member.1.Name=InstanceType
&MetricData.member.1.Dimensions.member.1.Value=m1.small
&AUTHPARAMS
```

So the dimensions need to be split between name and value and need their own prefix of `Dimensions.member.Name` and `Dimensions.member.Value`

**Comment by yumeto** [comment]
Thanks @CaldwellYSR , I've found the same issue about `Dimensions` mapping is incorrect.
(also timestamp, too)

But "MetricData.member" is parsed collectlly. I've commented to https://github.com/ex-aws/ex_aws_cloudwatch/pull/6.
